resources:
{{ range $i, $proxy := (ds "cnf").proxy -}}
- "@type": type.googleapis.com/envoy.config.cluster.v3.Cluster
  name: {{ $proxy.name }}
  type: STRICT_DNS
  connect_timeout: 1s
  lb_policy: ROUND_ROBIN
  typed_extension_protocol_options:
    envoy.extensions.upstreams.http.v3.HttpProtocolOptions:
      "@type": type.googleapis.com/envoy.extensions.upstreams.http.v3.HttpProtocolOptions
      explicit_http_config:
        http2_protocol_options: {}
  load_assignment:
    cluster_name: {{ $proxy.name }}
    endpoints:
    - lb_endpoints:
      - endpoint:
          address:
            socket_address:
              address: {{ $proxy.host }}
              port_value: {{ $proxy.port }}
{{ end }}
