resources:
{{ range $i, $proxy := (ds "cnf").proxy -}}
- "@type": type.googleapis.com/envoy.config.listener.v3.Listener
  name: {{ $proxy.name }}
  address:
    socket_address:
      address: 0.0.0.0
      port_value: {{ $proxy.listen }}
  filter_chains:
  - filters:
    - name: envoy.filters.network.tcp_proxy
      typed_config:
        "@type": type.googleapis.com/envoy.extensions.filters.network.tcp_proxy.v3.TcpProxy
        stat_prefix: tcp
        cluster: {{ $proxy.name }}
{{ end }}
